# A conda environment for ESPIn lessons.
#
# Usage:
#   $ conda env create --file=environment.yaml
#   $ source activate espin

name: tectonics_env
channels:
  - default
dependencies:
  - numpy	
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - pickle
  - yaml
  - rasterio
  - landlab
